### ISSUE TITLE
Karaoke - Alphabetical scroller starts to get off track after letter "C"

### ISSUE THREAD

**Issue by eegraf** [challfry/TheKraken#16]
See video. When user taps a letter I would assume I would be put into the list at that letter. For selections near the top of the list this is true, but from about C on you are dropped far from the expected entry point . For example I tap & hold U and the suggested artist is Shaggy & Ricardo. Tis also leads to user being able to scroll off the bottom of the screen. 

https://drive.google.com/file/d/1rVmPGhkHUM4WUdYL7upt2oUTkkjGJ7UZ/view?usp=sharing

**Comment by challfry** [comment]
I am currently building the index on the right by evenly spacing all the letters in the alphabet, plus the "1" at the top which is a placeholder for all the numerals as well as special characters--songs that start with #, or (.

This of course doesn't match the actual distribution first characters of songs/artists in the table. The problem is, when you filter the songs/artists, the distribution changes, and it takes too long to recalculate where each index element should be. Plus, it'll look weird when the index elements are unevenly spaced--that is, when each index letter is placed at its relative position in the index view to match its position in the list.

So. 1) It's easier this way. 2) It'll look weird the other way, and be slow 3) Since we show the actual landing point while scrubbing the index, I think we're okay.
