### ISSUE TITLE
APP iPad Cannot create Calendar event

### ISSUE THREAD

**Issue by eegraf** [challfry/TheKraken#29]
No idea what is going on, but cannot create a calendar event from iPad. 
Attempted at 7:43 1/27/2020

![IMG_0011](https://user-images.githubusercontent.com/1618900/73234019-336fd900-413d-11ea-8cc3-d17c43aef8f9.PNG)

**Comment by challfry** [comment]
Of course, because Local calendar items are disabled when iCloud calendars are turned on. 

When you create a calendar with the API, you have to declare a 'source'. A source is a container for a bunch of calendar data, and is something like "local", "exchange", "calDAV", "mobileMe". I figured 'local' was the right choice, as users would want the calendar event just on their local device with minimum fuss. But no.

Also, the idea is that "Joco Calendar" can be easily deleted in Calendar after the cruise, if the user wants to not have all that crap in their calendar.

Anyway, the code now tries to use the default calendar source. Should work with iCloud now.
