### ISSUE TITLE
APP Spokes are not dismissed so tapping Today gets you a spoke, not expected result

### ISSUE THREAD

**Issue by eegraf** [challfry/TheKraken#39]
Kinda weird, and edgy...
Start on Today, then tap Deck Maps (or Games or...)
From TabBar tap Forums
From Tabbar now tap Today
Expected>Today . Actual>Deck maps

**Comment by challfry** [comment]
This is actually expected behavior. You can tap on a tab again to go to the root of that tab's navstack.

Many apps hide the tab bar when you're not at the root of the navstack, because easily moving around the app is somehow bad. When each tab is a navstack, you can click into content on each tab. Tapping a tab bar icon once switches tabs but doesn't unwind the navstack on that tab, instead it shows you the view you were at last in that tab. Tapping the same tab again unwinds the navstack to the root.

I think there may be an issue here in that some of the cells in the Daily view switch tabs and some do nav pushes. The fix is going to be to get rid of cells that are also tabs.
