### ISSUE TITLE
App Beta 6 Edit profile Save button does not return you to User profile as expected

### ISSUE THREAD

**Issue by eegraf** [challfry/TheKraken#43]
In edit profile, you enter all the data and tap Save and nothing SEEMS to happen. Apparently the data IS saved

**Comment by eegraf** [comment]
Turns out the data is NOT saved, there is an error from the server

**Comment by challfry** [comment]
Still doesn't return you to the profile page, but it does show a progress cell, and if there's errors it shows them next to the fields that cause them. I kinda don't want to exit the profile edit screen in this case since you also edit your profile pic from there.

Anyway, try it out, and just reopen it if you think we should exit.
